version: "2"

services:
  cuckoo-worker:
    #logging:
    #  driver: syslog
    restart: always
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/vboxdrv:/dev/vboxdrv"
    build:
      context: ./cuckoo-worker
    image: harryr/cockatoo:cuckoo-worker
    ports:
      - "8090:8090"
    links:
      - cuckoo-dist
    networks:
      - cuckoo
    tmpfs:
      - /tmp
    volumes:
      - ../cuckoo-worker-storage:/cuckoo/storage/
      - ../vmcloak-persistent:/root/.vmcloak/
      - ../cuckoo-worker-vms:/root/.vmcloak/vms/

  cuckoo-dist:
    #logging:
    #  driver: syslog
    restart: always
    depends_on:
      - cuckoo-dist-db
    build:
      context: ./cuckoo-dist
    image: harryr/cockatoo:cuckoo-dist
    ports:
      - "9003:9003"
    links:
      - cuckoo-dist-db:db
    networks:
      - cuckoo
    tmpfs:
      - /tmp

  cuckoo-dist-db:
    #logging:
    #  driver: syslog
    restart: always
    build:
      context: ./postgresql
    image: harryr/cockatoo:postgresql
    ports:
      - "5432:5432"
    networks:
      - cuckoo

networks:
  cuckoo:
    driver: host