FROM harryr/cockatoo:virtualbox5
MAINTAINER Harry Roberts <harry.roberts@xiphosresearch.co.uk>

RUN apt-get -y install mkisofs genisoimage python2.7 python-pip

RUN apt-get clean 

RUN pip install vmcloak
